# Analyzing Customer Data
You are working with customer data for an e-commerce company. The data includes customer IDs, ages, and purchase amounts. Your task is to create NumPy arrays to store and analyze this data.

1. Create a 1-dimensional NumPy array called customer_ids that contains the following customer IDs: 1001, 1002, 1003, 1004, 1005.

In [35]:
import numpy as np

In [36]:
customer_id=np.array([1001,1002,1003,1004,1005])
customer_id

array([1001, 1002, 1003, 1004, 1005])

2. Create a 1-dimensional NumPy array called ages that contains the ages of the customers: 25, 30, 35, 40, 45. Use the np.arange() function to create this array.

In [37]:
age_customers=np.arange(25,50,5)
age_customers

array([25, 30, 35, 40, 45])

3. Create a 2-dimensional NumPy array called purchase_amounts that contains the purchase amounts for each customer over three months:

- Month 1: 100, 200, 300, 400, 500
- Month 2: 150, 250, 350, 450, 550
- Month 3: 200, 300, 400, 500, 600

In [38]:
month1=np.arange(100,600,100)
month2=np.arange(150,551,100)
month3=np.arange(200,700,100)
purchase_amounts=np.array([month1,month2,month3])
purchase_amounts

array([[100, 200, 300, 400, 500],
       [150, 250, 350, 450, 550],
       [200, 300, 400, 500, 600]])

4. Create a 3-dimensional NumPy array called sales_data that combines the customer IDs, ages, and purchase amounts. The shape of the array should be (4, 5, 2), where:

- The first dimension represents the customers
- The second dimension represents the months
- The third dimension represents the customer ID and age for each customer

In [39]:
sales_data=np.array([
                     [[customer_id[i],age_customers[i]] for i in range(5)],
                     [[customer_id[i],purchase_amounts[0][i]] for i in range(5)],
                     [[customer_id[i],purchase_amounts[1][i]] for i in range(5)],
                     [[customer_id[i],purchase_amounts[2][i]] for i in range(5)]
                     ])
sales_data

array([[[1001,   25],
        [1002,   30],
        [1003,   35],
        [1004,   40],
        [1005,   45]],

       [[1001,  100],
        [1002,  200],
        [1003,  300],
        [1004,  400],
        [1005,  500]],

       [[1001,  150],
        [1002,  250],
        [1003,  350],
        [1004,  450],
        [1005,  550]],

       [[1001,  200],
        [1002,  300],
        [1003,  400],
        [1004,  500],
        [1005,  600]]])

5. Create a NumPy array called large_purchases that contains the purchase amounts greater than 300. Use boolean indexing to create this array.

In [40]:
mask=purchase_amounts>300
purchase_amounts[mask]

array([400, 500, 350, 450, 550, 400, 500, 600])

6. Create a random integer array called random_purchases with shape (3, 5) that represents random purchase amounts between 100 and 1000.

In [41]:
random_purchases=np.random.randint(100,1000,size=(3,5))
random_purchases

array([[710, 513, 215, 623, 495],
       [906, 493, 432, 105, 180],
       [452, 313, 891, 674, 198]], dtype=int32)