# Broadcasting:

1. Create a 2D NumPy array arr1 with shape (3, 4) filled with random integers between 1 and 10 (inclusive).

In [1]:
import numpy as np

In [2]:
arr1=np.array((np.random.randint(1,11,size=(3,4))))
print('Array1 :',arr1)

Array1 : [[ 6  6  9  4]
 [ 2 10  9 10]
 [ 4  9  1  7]]


2. Create a 1D NumPy array arr2 with shape (4,) filled with the values [2, 4, 6, 8].

In [3]:
arr2=np.array([2,4,6,8])
print('Array2 :',arr2)

Array2 : [2 4 6 8]


3. Perform element-wise addition between arr1 and arr2 using broadcasting and store the result in a new array result1.

In [4]:
result1=arr1+arr2
print('Result1 :',result1)

Result1 : [[ 8 10 15 12]
 [ 4 14 15 18]
 [ 6 13  7 15]]


4. Create a 2D NumPy array arr3 with shape (3, 1) filled with the values [10, 20, 30].

In [5]:
arr3=np.array([[10],[20],[30]])
print('Array3 :',arr3)

Array3 : [[10]
 [20]
 [30]]


5. Perform element-wise multiplication between arr1 and arr3 using broadcasting and store the result in a new array result2.

In [6]:
result2=arr1*arr3
print('Result2 :',result2)

Result2 : [[ 60  60  90  40]
 [ 40 200 180 200]
 [120 270  30 210]]


6. Create a scalar value scalar with the value 5.

In [7]:
scalar=5
print('Scalar :',scalar)

Scalar : 5


7. Subtract scalar from each element of result1 using broadcasting and store the result in a new array result3.

In [8]:
result3=result1-scalar
print('Result3 :',result3)

Result3 : [[ 3  5 10  7]
 [-1  9 10 13]
 [ 1  8  2 10]]
