# Analyzing Temperature Data
You are given a NumPy array temperatures that contains the daily temperature readings for a city over a period of one week. The array has shape (7, 24), representing 7 days and 24 hourly temperature readings per day.

In [9]:
import numpy as np

temperatures = np.array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
                         [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
                         [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                          25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
                         [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                          26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
                         [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                          27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
                         [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17],
                         [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                          29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18]])

1. Extract the temperature readings for the first day.

In [10]:
first_day=temperatures[0,:]
print('The temperatures of first day is :\n',first_day)

The temperatures of first day is :
 [12 14 15 16 17 18 19 20 21 22 23 24 23 22 21 20 19 18 17 16 15 14 13 12]


2. Extract the temperature readings for the last day.

In [11]:
last_day=temperatures[-1,:]
print('The temperatures of last day is :\n',last_day)

The temperatures of last day is :
 [18 20 21 22 23 24 25 26 27 28 29 30 29 28 27 26 25 24 23 22 21 20 19 18]


3. Extract the temperature readings for the first 12 hours of each day.

In [12]:
twelve_hours=temperatures[:,:12]
print('The first 12 hours of each day is :\n',twelve_hours)

The first 12 hours of each day is :
 [[12 14 15 16 17 18 19 20 21 22 23 24]
 [13 15 16 17 18 19 20 21 22 23 24 25]
 [14 16 17 18 19 20 21 22 23 24 25 26]
 [15 17 18 19 20 21 22 23 24 25 26 27]
 [16 18 19 20 21 22 23 24 25 26 27 28]
 [17 19 20 21 22 23 24 25 26 27 28 29]
 [18 20 21 22 23 24 25 26 27 28 29 30]]


4. Extract the temperature readings for the last 6 hours of each day.

In [13]:
six_hours=temperatures[:,-6:]
print('The last 6 hours of each day is :\n',six_hours)

The last 6 hours of each day is :
 [[17 16 15 14 13 12]
 [18 17 16 15 14 13]
 [19 18 17 16 15 14]
 [20 19 18 17 16 15]
 [21 20 19 18 17 16]
 [22 21 20 19 18 17]
 [23 22 21 20 19 18]]


5. Extract the temperature readings for every other hour of the fourth day.

In [14]:
forth_day=temperatures[3,::2]
print('Every other hour of the fourth day is :\n',forth_day)

Every other hour of the fourth day is :
 [15 18 20 22 24 26 26 24 22 20 18 16]


6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher.

In [15]:
temperatures[4,:3]+=10
print('The first 3 hours of the fifth day to be 10 degrees higher is :\n',temperatures[4,:])

The first 3 hours of the fifth day to be 10 degrees higher is :
 [26 28 29 20 21 22 23 24 25 26 27 28 27 26 25 24 23 22 21 20 19 18 17 16]


7. Create a boolean mask to find all temperature readings above 25 degrees.

In [16]:
above_25_degree=temperatures>25
print('Create a boolean mask to find all temperature readings above 25 degrees :\n',temperatures[above_25_degree])

Create a boolean mask to find all temperature readings above 25 degrees :
 [26 26 27 26 26 28 29 26 27 28 27 26 26 27 28 29 28 27 26 26 27 28 29 30
 29 28 27 26]
