# Analyzing Sales Data:
You are given two NumPy arrays sales_2021 and sales_2022 that contain the monthly sales data for a company over the past two years. Each array has shape (3, 4), representing sales data for 3 products over 4 quarters.

In [1]:
import numpy as np

sales_2021 = np.array([[100, 120, 140, 160],
                       [200, 220, 240, 260],
                       [300, 320, 340, 360]])

sales_2022 = np.array([[110, 130, 150, 170],
                       [210, 230, 250, 270],
                       [310, 330, 350, 370]])


1. Combine the sales data for both years into a single array using vertical stacking.

In [2]:
combine_sales=np.vstack((sales_2021,sales_2022))
print('The sales data for both years into a single array :',combine_sales)

The sales data for both years into a single array : [[100 120 140 160]
 [200 220 240 260]
 [300 320 340 360]
 [110 130 150 170]
 [210 230 250 270]
 [310 330 350 370]]


2. Reshape the combined sales data into a 1D array.

In [3]:
print('The combined sales data into a 1D array :',combine_sales.reshape(-1))

The combined sales data into a 1D array : [100 120 140 160 200 220 240 260 300 320 340 360 110 130 150 170 210 230
 250 270 310 330 350 370]


3. Split the combined sales data into separate arrays for each product using horizontal splitting.

In [4]:
for i in range(3):
    print(f'product {i+1} :\n{combine_sales[[i, i + 3],:]}')

product 1 :
[[100 120 140 160]
 [110 130 150 170]]
product 2 :
[[200 220 240 260]
 [210 230 250 270]]
product 3 :
[[300 320 340 360]
 [310 330 350 370]]


4. Create a new array that repeats the sales data for each year twice using tiling.

In [5]:
each_year=np.tile(combine_sales,(1,2))
print('Tiled sales data :',each_year)

Tiled sales data : [[100 120 140 160 100 120 140 160]
 [200 220 240 260 200 220 240 260]
 [300 320 340 360 300 320 340 360]
 [110 130 150 170 110 130 150 170]
 [210 230 250 270 210 230 250 270]
 [310 330 350 370 310 330 350 370]]


5. Calculate the total sales for each year using flattening and summation.

In [6]:
total_sales_2021=np.sum(sales_2021.flatten())
total_sales_2022=np.sum(sales_2022.flatten())
print('Total sales of 2021 :',total_sales_2021,'\nTotal sales of 2021 :',total_sales_2022)

Total sales of 2021 : 2760 
Total sales of 2021 : 2880
